// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  userGuideSidebar: [
    {
      type: "autogenerated",
      dirName: "user-guide",
    },
  ],
  productSpecSidebar: [
    {
      type: "autogenerated",
      dirName: "product-spec",
    },
  ],
  systemDesignSidebar: [
    {
      type: "autogenerated",
      dirName: "system-design",
    },
  ],
  techSpecsSidebar: [
    {
      type: "autogenerated",
      dirName: "tech-specs",
    },
  ],
  apiSpecSidebar: [
    {
      type: "autogenerated",
      dirName: "api-spec",
    },
  ],
  dataSpecSidebar: [
    {
      type: "autogenerated",
      dirName: "data-spec",
    },
  ],
  securitySpecSidebar: [
    {
      type: "autogenerated",
      dirName: "security-spec",
    },
  ],
  testSpecSidebar: [
    {
      type: "autogenerated",
      dirName: "test-spec",
    },
  ],
  adrSidebar: [
    {
      type: "autogenerated",
      dirName: "adr",
    },
  ],
};

module.exports = sidebars;
